
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATTRIBUTE COMPARE DATE EXCLUDE MEASURE VALUEstatement : ATTRIBUTE DATEstatement : ATTRIBUTE ATTRIBUTE DATE\n                | MEASURE ATTRIBUTE DATEstatement : ATTRIBUTE DATE DATEstatement : ATTRIBUTE ATTRIBUTE DATE DATE\n                | MEASURE ATTRIBUTE DATE DATE statement : MEASURE VALUE\n                | ATTRIBUTE VALUE  statement : VALUE MEASURE\n                | VALUE ATTRIBUTE  statement : MEASURE VALUE EXCLUDE\n                | ATTRIBUTE VALUE EXCLUDE  statement : MEASURE EXCLUDE VALUE\n                | ATTRIBUTE EXCLUDE VALUE  statement : EXCLUDE MEASURE VALUE\n                | EXCLUDE ATTRIBUTE VALUE  statement : MEASURE EXCLUDE ATTRIBUTE VALUE\n                | ATTRIBUTE EXCLUDE MEASURE VALUE\n                | ATTRIBUTE EXCLUDE ATTRIBUTE VALUE\n                | MEASURE EXCLUDE MEASURE VALUE  statement : ATTRIBUTE VALUE MEASURE\n                | MEASURE VALUE ATTRIBUTE\n                | ATTRIBUTE VALUE ATTRIBUTE  statement : ATTRIBUTE MEASURE VALUE\n                | MEASURE ATTRIBUTE VALUE\n                | ATTRIBUTE ATTRIBUTE VALUE  statement : ATTRIBUTE VALUE MEASURE VALUE\n                | MEASURE VALUE ATTRIBUTE VALUE\n                | ATTRIBUTE VALUE ATTRIBUTE VALUE statement : ATTRIBUTE COMPARE MEASURE\n                | MEASURE COMPARE ATTRIBUTE\n                | ATTRIBUTE COMPARE ATTRIBUTE  statement : COMPARE MEASURE\n                | COMPARE ATTRIBUTE '
    
_lr_action_items = {'COMPARE':([0,2,5,],[1,9,17,]),'ATTRIBUTE':([0,1,2,3,5,6,9,11,14,17,19,20,],[2,7,10,15,18,21,23,27,32,35,39,40,]),'VALUE':([0,2,5,10,12,14,18,20,21,22,27,28,32,33,39,40,42,],[3,11,19,26,30,34,37,41,43,44,46,47,48,49,51,52,53,]),'MEASURE':([0,1,2,3,6,9,11,14,20,],[5,8,12,16,22,24,28,33,42,]),'DATE':([2,10,13,18,25,36,],[13,25,31,36,45,50,]),'EXCLUDE':([0,2,5,11,19,],[6,14,20,29,38,]),'$end':([4,7,8,11,13,15,16,19,23,24,25,26,27,28,29,30,31,34,35,36,37,38,39,41,43,44,45,46,47,48,49,50,51,52,53,],[0,-34,-33,-8,-1,-10,-9,-7,-32,-30,-2,-26,-23,-21,-12,-24,-4,-14,-31,-3,-25,-11,-22,-13,-16,-15,-5,-29,-27,-19,-18,-6,-28,-17,-20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ATTRIBUTE DATE','statement',2,'p_statement_date','grammar.py',53),
  ('statement -> ATTRIBUTE ATTRIBUTE DATE','statement',3,'p_statement_attribute_date','grammar.py',62),
  ('statement -> MEASURE ATTRIBUTE DATE','statement',3,'p_statement_attribute_date','grammar.py',63),
  ('statement -> ATTRIBUTE DATE DATE','statement',3,'p_statement_date_date','grammar.py',71),
  ('statement -> ATTRIBUTE ATTRIBUTE DATE DATE','statement',4,'p_statement_attribute_date_date','grammar.py',80),
  ('statement -> MEASURE ATTRIBUTE DATE DATE','statement',4,'p_statement_attribute_date_date','grammar.py',81),
  ('statement -> MEASURE VALUE','statement',2,'p_statement_single','grammar.py',91),
  ('statement -> ATTRIBUTE VALUE','statement',2,'p_statement_single','grammar.py',92),
  ('statement -> VALUE MEASURE','statement',2,'p_statement_single_second','grammar.py',99),
  ('statement -> VALUE ATTRIBUTE','statement',2,'p_statement_single_second','grammar.py',100),
  ('statement -> MEASURE VALUE EXCLUDE','statement',3,'p_statement_exclude','grammar.py',106),
  ('statement -> ATTRIBUTE VALUE EXCLUDE','statement',3,'p_statement_exclude','grammar.py',107),
  ('statement -> MEASURE EXCLUDE VALUE','statement',3,'p_statement_exclude_middle','grammar.py',113),
  ('statement -> ATTRIBUTE EXCLUDE VALUE','statement',3,'p_statement_exclude_middle','grammar.py',114),
  ('statement -> EXCLUDE MEASURE VALUE','statement',3,'p_statement_exclude_first','grammar.py',120),
  ('statement -> EXCLUDE ATTRIBUTE VALUE','statement',3,'p_statement_exclude_first','grammar.py',121),
  ('statement -> MEASURE EXCLUDE ATTRIBUTE VALUE','statement',4,'p_statement_exclude_large','grammar.py',127),
  ('statement -> ATTRIBUTE EXCLUDE MEASURE VALUE','statement',4,'p_statement_exclude_large','grammar.py',128),
  ('statement -> ATTRIBUTE EXCLUDE ATTRIBUTE VALUE','statement',4,'p_statement_exclude_large','grammar.py',129),
  ('statement -> MEASURE EXCLUDE MEASURE VALUE','statement',4,'p_statement_exclude_large','grammar.py',130),
  ('statement -> ATTRIBUTE VALUE MEASURE','statement',3,'p_statement_multiple_VALUE_second','grammar.py',137),
  ('statement -> MEASURE VALUE ATTRIBUTE','statement',3,'p_statement_multiple_VALUE_second','grammar.py',138),
  ('statement -> ATTRIBUTE VALUE ATTRIBUTE','statement',3,'p_statement_multiple_VALUE_second','grammar.py',139),
  ('statement -> ATTRIBUTE MEASURE VALUE','statement',3,'p_statement_multiple_value_third','grammar.py',146),
  ('statement -> MEASURE ATTRIBUTE VALUE','statement',3,'p_statement_multiple_value_third','grammar.py',147),
  ('statement -> ATTRIBUTE ATTRIBUTE VALUE','statement',3,'p_statement_multiple_value_third','grammar.py',148),
  ('statement -> ATTRIBUTE VALUE MEASURE VALUE','statement',4,'p_statement_multiple_value_four','grammar.py',155),
  ('statement -> MEASURE VALUE ATTRIBUTE VALUE','statement',4,'p_statement_multiple_value_four','grammar.py',156),
  ('statement -> ATTRIBUTE VALUE ATTRIBUTE VALUE','statement',4,'p_statement_multiple_value_four','grammar.py',157),
  ('statement -> ATTRIBUTE COMPARE MEASURE','statement',3,'p_statement_compare','grammar.py',164),
  ('statement -> MEASURE COMPARE ATTRIBUTE','statement',3,'p_statement_compare','grammar.py',165),
  ('statement -> ATTRIBUTE COMPARE ATTRIBUTE','statement',3,'p_statement_compare','grammar.py',166),
  ('statement -> COMPARE MEASURE','statement',2,'p_statement_compare_single','grammar.py',173),
  ('statement -> COMPARE ATTRIBUTE','statement',2,'p_statement_compare_single','grammar.py',174),
]
