# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=1000, null=True)),
                ('volume', models.FloatField(null=True)),
                ('deal_id', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('ev', models.IntegerField(null=True)),
            ],
        ),
    ]
